#docker-compose.yml
version: '3.7'
services:
  traefik:
    image: 'traefik:2.3'
    container_name: 'traefik'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/traefik.yml:/traefik.yml'
      - './traefik/traefik_dynamic.yml:/traefik_dynamic.yml'
      - './traefik/acme.json:/acme.json'
    networks:
      - proxy
    extra_hosts:
      - host.docker.internal:172.17.0.1
    labels:
        #enable the dashboard
      - "traefik.enable=true"
        # network traefik
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
        # domain for dashboard
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.jocadero.com`)"
        # enable password auth
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
        # points to dashboard
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
