version: "3.4"

services:
  nginx:
    image: nginx:alpine
    container_name: jocadero
    restart: unless-stopped
    volumes:
      - './jocadero/conf:/etc/nginx/conf.d'
      - './jocadero:/var/www/html'
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.nginx.rule=Host(`jocadero.com`, `www.jocadero.com`)" # domain to expose on
      - "traefik.http.routers.nginx.entrypoints=websecure"
    networks:
      - proxy

networks:
  proxy:
    external: true
